export const generateCritique = (dailyScore, _rankTitle, _stats) => {
  const score = dailyScore || 0;
  
  if (score >= 900) {
    return [
      "STATUS: ALPHA_RECOGNIZED.",
      "CRITIQUE: PEAK_PERFORMANCE_DETECTED. NO_SLACK_IDENTIFIED.",
      "TACTICAL_ADVICE: MAINTAIN_TRAJECTORY. OVER_PERFORMANCE_IS_THE_BASELINE."
    ];
  }
  
  if (score >= 700) {
    return [
      "STATUS: SIGMA_GRINDER.",
      "CRITIQUE: CONSISTENCY_IS_SOLID. MINIMAL_FRICTION_DETECTED.",
      "TACTICAL_ADVICE: PUSH_FOR_THE_LAST_10%. THE_GAP_BETWEEN_SIGMA_AND_ALPHA_IS_WILLPOWER."
    ];
  }
  
  if (score >= 500) {
    return [
      "STATUS: DREAMER.",
      "CRITIQUE: POTENTIAL_UNREALIZED. EXECUTION_FLAWED.",
      "TACTICAL_ADVICE: STOP_PLANNING_AND_START_EXECUTING. YOUR_AURA_IS_VULNERABLE."
    ];
  }
  
  if (score >= 300) {
    return [
      "STATUS: SLACKING.",
      "CRITIQUE: DISCIPLINE_COLLAPSE_DETECTED.",
      "TACTICAL_ADVICE: INITIATE_EMERGENCY_RECOVERY. ONE_MORE_DAY_OF_SLACKING_WILL_BREAK_THE_STREAK."
    ];
  }
  
  return [
    "STATUS: NORMIE_BETA.",
    "CRITIQUE: SYSTEM_FAILURE. NO_DATA_TO_ANALYZE.",
    "TACTICAL_ADVICE: WAKE_UP. YOU_ARE_CAUGHT_LACKING. REBOOT_YOUR_DISCIPLINE_IMMEDIATELY."
  ];
};
